export interface CatalogRecipe {
  name: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  prep_time_minutes: number;
  cook_time_minutes: number;
  servings: number;
  calories_per_serving: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  tags: string[];
  image_query: string; // Unsplash search term
}

export const RECIPE_CATALOG: CatalogRecipe[] = [
  {
    name: "Greek Chicken Bowl",
    description: "Juicy grilled chicken over rice with tzatziki, cucumber, and olives.",
    ingredients: ["chicken breast", "brown rice", "cucumber", "cherry tomatoes", "kalamata olives", "feta cheese", "tzatziki"],
    instructions: ["Season and grill chicken.", "Cook rice.", "Assemble bowl with all toppings.", "Drizzle with tzatziki."],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 2,
    calories_per_serving: 520,
    protein_g: 48,
    carbs_g: 42,
    fat_g: 14,
    tags: ["high protein", "meal prep", "mediterranean"],
    image_query: "greek chicken bowl",
  },
  {
    name: "Overnight Oats",
    description: "Creamy no-cook oats loaded with berries and chia seeds.",
    ingredients: ["rolled oats", "almond milk", "chia seeds", "blueberries", "strawberries", "honey", "vanilla extract"],
    instructions: ["Combine oats, milk, and chia seeds.", "Stir in vanilla and honey.", "Refrigerate overnight.", "Top with berries before serving."],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories_per_serving: 380,
    protein_g: 12,
    carbs_g: 58,
    fat_g: 10,
    tags: ["breakfast", "meal prep", "no-cook"],
    image_query: "overnight oats berries",
  },
  {
    name: "Salmon & Roasted Veggies",
    description: "Omega-3-rich salmon fillet with a colourful sheet-pan of vegetables.",
    ingredients: ["salmon fillet", "broccoli", "bell peppers", "zucchini", "olive oil", "garlic", "lemon", "herbs"],
    instructions: ["Preheat oven to 425°F.", "Toss veggies in olive oil.", "Add salmon to pan.", "Roast 20 minutes."],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 2,
    calories_per_serving: 440,
    protein_g: 42,
    carbs_g: 18,
    fat_g: 22,
    tags: ["high protein", "omega-3", "dinner", "sheet pan"],
    image_query: "salmon roasted vegetables",
  },
  {
    name: "Avocado Toast with Eggs",
    description: "Creamy avocado on whole-grain toast topped with poached eggs.",
    ingredients: ["whole grain bread", "avocado", "eggs", "cherry tomatoes", "red pepper flakes", "lemon juice", "salt"],
    instructions: ["Toast bread.", "Mash avocado with lemon and salt.", "Poach eggs.", "Assemble and garnish."],
    prep_time_minutes: 5,
    cook_time_minutes: 8,
    servings: 1,
    calories_per_serving: 410,
    protein_g: 18,
    carbs_g: 34,
    fat_g: 22,
    tags: ["breakfast", "quick", "vegetarian"],
    image_query: "avocado toast poached egg",
  },
  {
    name: "Black Bean Tacos",
    description: "Hearty plant-based tacos with cumin-spiced black beans and mango salsa.",
    ingredients: ["corn tortillas", "black beans", "mango", "red onion", "cilantro", "lime", "cumin", "avocado"],
    instructions: ["Warm beans with cumin and spices.", "Dice mango, onion, and cilantro for salsa.", "Warm tortillas.", "Assemble and squeeze lime."],
    prep_time_minutes: 15,
    cook_time_minutes: 10,
    servings: 3,
    calories_per_serving: 360,
    protein_g: 14,
    carbs_g: 52,
    fat_g: 10,
    tags: ["vegan", "quick", "mexican"],
    image_query: "black bean tacos",
  },
  {
    name: "Quinoa Power Salad",
    description: "Protein-packed quinoa with roasted chickpeas, kale, and lemon-tahini dressing.",
    ingredients: ["quinoa", "chickpeas", "kale", "cherry tomatoes", "cucumber", "tahini", "lemon", "olive oil"],
    instructions: ["Cook quinoa.", "Roast chickpeas at 400°F for 25 min.", "Massage kale.", "Whisk dressing and toss all together."],
    prep_time_minutes: 15,
    cook_time_minutes: 25,
    servings: 4,
    calories_per_serving: 390,
    protein_g: 16,
    carbs_g: 50,
    fat_g: 14,
    tags: ["vegan", "meal prep", "salad", "high fiber"],
    image_query: "quinoa chickpea salad",
  },
  {
    name: "Turkey & Veggie Stir-Fry",
    description: "Lean ground turkey with colourful vegetables in a savory ginger-soy sauce.",
    ingredients: ["ground turkey", "broccoli", "snap peas", "carrots", "ginger", "soy sauce", "sesame oil", "garlic", "brown rice"],
    instructions: ["Brown turkey in pan.", "Add veggies and cook 5 min.", "Add sauce ingredients.", "Serve over brown rice."],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    calories_per_serving: 430,
    protein_g: 36,
    carbs_g: 40,
    fat_g: 12,
    tags: ["high protein", "meal prep", "asian-inspired"],
    image_query: "turkey stir fry vegetables",
  },
  {
    name: "Green Smoothie Bowl",
    description: "Thick blended spinach and banana bowl topped with granola and seeds.",
    ingredients: ["spinach", "frozen banana", "mango chunks", "almond milk", "granola", "chia seeds", "coconut flakes", "honey"],
    instructions: ["Blend spinach, banana, mango, and milk until thick.", "Pour into bowl.", "Add toppings."],
    prep_time_minutes: 5,
    cook_time_minutes: 0,
    servings: 1,
    calories_per_serving: 360,
    protein_g: 10,
    carbs_g: 64,
    fat_g: 8,
    tags: ["breakfast", "vegan", "no-cook", "quick"],
    image_query: "green smoothie bowl granola",
  },
  {
    name: "Baked Lemon Herb Chicken",
    description: "Tender oven-baked chicken thighs marinated in lemon, garlic, and fresh herbs.",
    ingredients: ["chicken thighs", "lemon", "garlic", "rosemary", "thyme", "olive oil", "salt", "pepper"],
    instructions: ["Marinate chicken 30 min.", "Preheat oven to 400°F.", "Bake 35 min until golden.", "Rest 5 min before serving."],
    prep_time_minutes: 35,
    cook_time_minutes: 35,
    servings: 4,
    calories_per_serving: 390,
    protein_g: 44,
    carbs_g: 4,
    fat_g: 22,
    tags: ["high protein", "dinner", "meal prep", "gluten-free"],
    image_query: "lemon herb baked chicken",
  },
  {
    name: "Lentil & Veggie Soup",
    description: "Hearty red lentil soup with carrots, tomatoes, and warming spices.",
    ingredients: ["red lentils", "carrots", "celery", "onion", "tomatoes", "cumin", "turmeric", "vegetable broth", "spinach"],
    instructions: ["Sauté onion, carrot, celery.", "Add lentils, tomatoes, broth.", "Simmer 25 min.", "Stir in spinach and season."],
    prep_time_minutes: 10,
    cook_time_minutes: 30,
    servings: 6,
    calories_per_serving: 280,
    protein_g: 16,
    carbs_g: 44,
    fat_g: 4,
    tags: ["vegan", "high fiber", "meal prep", "soup"],
    image_query: "red lentil soup",
  },
  {
    name: "Shrimp & Zoodle Bowl",
    description: "Light and fresh zucchini noodles with garlic shrimp and cherry tomatoes.",
    ingredients: ["shrimp", "zucchini", "cherry tomatoes", "garlic", "olive oil", "parmesan", "basil", "red pepper flakes"],
    instructions: ["Spiralise zucchini.", "Sauté garlic and shrimp.", "Add tomatoes.", "Toss with zoodles and finish with parmesan."],
    prep_time_minutes: 10,
    cook_time_minutes: 10,
    servings: 2,
    calories_per_serving: 320,
    protein_g: 34,
    carbs_g: 16,
    fat_g: 14,
    tags: ["low carb", "quick", "seafood"],
    image_query: "shrimp zucchini noodles",
  },
  {
    name: "Sweet Potato & Black Bean Burrito",
    description: "Filling roasted sweet potato and black bean burritos with avocado crema.",
    ingredients: ["flour tortillas", "sweet potato", "black beans", "corn", "avocado", "sour cream", "lime", "cumin", "chili powder"],
    instructions: ["Roast diced sweet potato.", "Warm beans with spices.", "Blend avocado and sour cream.", "Assemble and wrap burritos."],
    prep_time_minutes: 10,
    cook_time_minutes: 25,
    servings: 4,
    calories_per_serving: 480,
    protein_g: 16,
    carbs_g: 72,
    fat_g: 14,
    tags: ["vegetarian", "meal prep", "filling"],
    image_query: "sweet potato black bean burrito",
  },
  {
    name: "Tuna Poke Bowl",
    description: "Fresh sushi-grade tuna over sushi rice with edamame, avocado, and sesame.",
    ingredients: ["sushi-grade tuna", "sushi rice", "edamame", "avocado", "cucumber", "soy sauce", "sesame oil", "sriracha", "sesame seeds"],
    instructions: ["Cook sushi rice.", "Cube tuna and marinate in soy and sesame.", "Assemble bowls with all toppings."],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 2,
    calories_per_serving: 510,
    protein_g: 38,
    carbs_g: 50,
    fat_g: 16,
    tags: ["high protein", "seafood", "fresh"],
    image_query: "tuna poke bowl",
  },
  {
    name: "Egg White Frittata",
    description: "Fluffy baked egg white frittata packed with spinach, mushrooms, and feta.",
    ingredients: ["egg whites", "spinach", "mushrooms", "feta cheese", "red onion", "garlic", "olive oil", "herbs"],
    instructions: ["Sauté veggies.", "Pour egg whites over.", "Crumble feta on top.", "Bake at 375°F for 20 min."],
    prep_time_minutes: 10,
    cook_time_minutes: 20,
    servings: 4,
    calories_per_serving: 180,
    protein_g: 22,
    carbs_g: 8,
    fat_g: 6,
    tags: ["high protein", "low calorie", "breakfast", "gluten-free"],
    image_query: "egg white frittata spinach",
  },
  {
    name: "Mango Chia Pudding",
    description: "Creamy coconut chia pudding layered with fresh mango puree.",
    ingredients: ["chia seeds", "coconut milk", "mango", "honey", "vanilla extract", "lime zest"],
    instructions: ["Whisk chia seeds into coconut milk.", "Refrigerate 4 hours.", "Blend mango with lime.", "Layer and serve."],
    prep_time_minutes: 10,
    cook_time_minutes: 0,
    servings: 2,
    calories_per_serving: 290,
    protein_g: 8,
    carbs_g: 36,
    fat_g: 14,
    tags: ["vegan", "no-cook", "breakfast", "snack"],
    image_query: "mango chia pudding",
  },
  {
    name: "Chicken Caesar Wrap",
    description: "Classic Caesar salad wrapped up with grilled chicken for a portable lunch.",
    ingredients: ["whole wheat tortilla", "grilled chicken breast", "romaine lettuce", "parmesan", "caesar dressing", "croutons"],
    instructions: ["Warm tortilla.", "Toss romaine with caesar dressing.", "Layer chicken and parmesan.", "Roll tightly and slice."],
    prep_time_minutes: 10,
    cook_time_minutes: 12,
    servings: 1,
    calories_per_serving: 450,
    protein_g: 40,
    carbs_g: 36,
    fat_g: 16,
    tags: ["high protein", "lunch", "quick"],
    image_query: "chicken caesar wrap",
  },
  {
    name: "Cauliflower Fried Rice",
    description: "Light cauliflower rice stir-fried with egg, vegetables, and soy sauce.",
    ingredients: ["cauliflower", "eggs", "frozen peas", "carrots", "green onion", "soy sauce", "sesame oil", "ginger", "garlic"],
    instructions: ["Rice the cauliflower in a food processor.", "Stir-fry veggies and push aside.", "Scramble eggs.", "Add cauliflower and sauce."],
    prep_time_minutes: 10,
    cook_time_minutes: 15,
    servings: 4,
    calories_per_serving: 190,
    protein_g: 12,
    carbs_g: 20,
    fat_g: 8,
    tags: ["low carb", "vegetarian", "quick"],
    image_query: "cauliflower fried rice",
  },
  {
    name: "Turkey Meatball Bowl",
    description: "Lean turkey meatballs over spiralised zoodles with marinara sauce.",
    ingredients: ["ground turkey", "egg", "breadcrumbs", "parmesan", "garlic", "zucchini", "marinara sauce", "basil"],
    instructions: ["Mix and roll meatballs.", "Bake at 400°F for 20 min.", "Spiralise zucchini.", "Serve meatballs over zoodles with sauce."],
    prep_time_minutes: 15,
    cook_time_minutes: 20,
    servings: 4,
    calories_per_serving: 360,
    protein_g: 34,
    carbs_g: 20,
    fat_g: 16,
    tags: ["high protein", "low carb", "dinner", "meal prep"],
    image_query: "turkey meatballs zucchini",
  },
];
