export interface CatalogWorkout {
  name: string;
  type: string;
  duration_minutes: number;
  calories_burned: number;
  description: string;
  video_id: string; // YouTube video ID
  channel: string;
  tags: string[];
}

export const WORKOUT_CATALOG: CatalogWorkout[] = [
  {
    name: "30-Min Full Body HIIT",
    type: "hiit",
    duration_minutes: 30,
    calories_burned: 350,
    description: "High-intensity full body workout, no equipment needed.",
    video_id: "ml6cT4AZdqI",
    channel: "MadFit",
    tags: ["full body", "no equipment", "beginner-friendly"],
  },
  {
    name: "20-Min Morning Yoga Flow",
    type: "yoga",
    duration_minutes: 20,
    calories_burned: 120,
    description: "Energising morning yoga to wake up your body and mind.",
    video_id: "4pKly2JojMw",
    channel: "Yoga With Adriene",
    tags: ["morning", "flexibility", "mindfulness"],
  },
  {
    name: "45-Min Upper Body Strength",
    type: "strength",
    duration_minutes: 45,
    calories_burned: 280,
    description: "Dumbbell upper body workout targeting chest, back, and arms.",
    video_id: "vc1E5CfRfos",
    channel: "Heather Robertson",
    tags: ["upper body", "dumbbells", "strength"],
  },
  {
    name: "30-Min Lower Body Sculpt",
    type: "strength",
    duration_minutes: 30,
    calories_burned: 250,
    description: "Glutes, quads, and hamstrings — no gym required.",
    video_id: "5BTf0LbVVhI",
    channel: "Heather Robertson",
    tags: ["lower body", "glutes", "no equipment"],
  },
  {
    name: "20-Min Cardio Dance",
    type: "cardio",
    duration_minutes: 20,
    calories_burned: 200,
    description: "Fun, dancey cardio session to burn calories without the treadmill.",
    video_id: "AHkVH4Piqhc",
    channel: "MadFit",
    tags: ["cardio", "dance", "fun"],
  },
  {
    name: "30-Min Pilates Core",
    type: "pilates",
    duration_minutes: 30,
    calories_burned: 180,
    description: "Pilates-inspired core workout for a strong, stable midsection.",
    video_id: "g_tea8ZNk5A",
    channel: "Move with Nicole",
    tags: ["core", "pilates", "abs"],
  },
  {
    name: "10-Min Abs Blast",
    type: "strength",
    duration_minutes: 10,
    calories_burned: 100,
    description: "Quick but brutal core finisher — great to add to any workout.",
    video_id: "DHD1-2P94DI",
    channel: "MadFit",
    tags: ["abs", "core", "quick"],
  },
  {
    name: "45-Min Full Body Strength",
    type: "strength",
    duration_minutes: 45,
    calories_burned: 320,
    description: "Compound lifts with dumbbells for total body conditioning.",
    video_id: "UBMk30rjy0o",
    channel: "Heather Robertson",
    tags: ["full body", "dumbbells", "compound"],
  },
  {
    name: "30-Min Beginner Running Plan",
    type: "running",
    duration_minutes: 30,
    calories_burned: 280,
    description: "Walk/run intervals designed for beginners building endurance.",
    video_id: "kVnyY17VS9Y",
    channel: "The Run Experience",
    tags: ["running", "beginner", "cardio"],
  },
  {
    name: "20-Min Stretch & Flexibility",
    type: "yoga",
    duration_minutes: 20,
    calories_burned: 80,
    description: "Deep stretching routine to improve mobility and reduce soreness.",
    video_id: "g_tea8ZNk5A",
    channel: "Yoga With Adriene",
    tags: ["flexibility", "recovery", "stretching"],
  },
  {
    name: "25-Min HIIT Cardio Burn",
    type: "hiit",
    duration_minutes: 25,
    calories_burned: 300,
    description: "Tabata-style intervals to spike your heart rate and torching fat.",
    video_id: "TkaYafQ-XC4",
    channel: "Sydney Cummings",
    tags: ["hiit", "cardio", "fat burn"],
  },
  {
    name: "30-Min Cycling Endurance",
    type: "cycling",
    duration_minutes: 30,
    calories_burned: 310,
    description: "Indoor cycling session with varying intensity zones.",
    video_id: "lJbANnUFd1o",
    channel: "Global Cycling Network",
    tags: ["cycling", "cardio", "endurance"],
  },
  {
    name: "20-Min Yoga for Stress Relief",
    type: "yoga",
    duration_minutes: 20,
    calories_burned: 90,
    description: "Gentle flow focused on releasing tension and calming the nervous system.",
    video_id: "hJbRpHZr_d0",
    channel: "Yoga With Adriene",
    tags: ["stress", "yoga", "mindfulness", "gentle"],
  },
  {
    name: "40-Min Legs & Glutes",
    type: "strength",
    duration_minutes: 40,
    calories_burned: 300,
    description: "Targeted lower body session with resistance band and bodyweight moves.",
    video_id: "2pLT-olgUJs",
    channel: "Heather Robertson",
    tags: ["legs", "glutes", "resistance band"],
  },
  {
    name: "15-Min Morning Mobility",
    type: "yoga",
    duration_minutes: 15,
    calories_burned: 70,
    description: "Quick joint mobility routine to start your day pain-free and energised.",
    video_id: "4pKly2JojMw",
    channel: "Tom Merrick",
    tags: ["mobility", "morning", "quick"],
  },
];
